import {StyleSheet} from 'react-native';
import {
  height,
  normalize,
  respFontSize,
  responsiveHeight,
  responsiveWidth,
} from '../../Utils/responsiveSize';
import {COLORS} from '../../Utils/Color';

export const styles = StyleSheet.create({
  mainView: {
    flex: 1,
    borderRadius: normalize(20),
    backgroundColor: COLORS.white,
    width: '100%',
  },
  logotView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: normalize(16),
    paddingBottom: normalize(16),
    paddingHorizontal: normalize(16),
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.lightGray,
  },
  titleView: {justifyContent: 'center', flex: 0.66},
  titleText: {
    fontSize: respFontSize(14),
    fontWeight: '600',
    color: COLORS.blackGray,
  },
  subTitle: {
    fontSize: respFontSize(10),
    fontWeight: '400',
    color: COLORS.gray1,
  },
  refreshBtn: {
    borderRadius: 20,
    backgroundColor: COLORS.gray3,
    justifyContent: 'center',
    height: 30,
    paddingHorizontal: 10,
    alignSelf: 'center',
  },
  refreshText: {
    fontSize: respFontSize(10),
    fontWeight: '600',
    color: COLORS.blue1,
  },
  inAppText: {
    fontSize: respFontSize(6),
    fontWeight: '400',
    color: COLORS.gray1,
    textAlign: 'center',
    alignSelf: 'center',
    paddingTop: normalize(4),
  },
  paddingHorizontal: {
    paddingHorizontal: normalize(16),
  },
  mainImage: {
    height: height / 1.8,
    width: '100%',
    backgroundColor: COLORS.black,
  },
  logoImg: {
    height: responsiveHeight(80),
    width: responsiveWidth(80),
    borderRadius: normalize(14),
    alignSelf: 'center',
  },
  alignCenter: {
    alignSelf: 'center',
  },
  bottomView: {
    flex: 1,
    width: '100%',
    padding: normalize(16),
    marginTop: 20,
    backgroundColor: COLORS.gray3,
  },
  bottomTitleView: {gap: 5, paddingTop: 5},
  bottomTitle: {
    fontSize: respFontSize(14),
    fontWeight: '600',
    color: COLORS.black,
    textAlign: 'center',
  },
  bottomSubTitleTxt: {
    fontSize: respFontSize(12),
    fontWeight: '400',
    color: COLORS.grey2,
    textAlign: 'center',
  },
  bottomRefreshTxtView: {justifyContent: 'center', paddingTop: 12},
  refreshTxtBtn: {
    borderRadius: 20,
    backgroundColor: COLORS.blue1,
    justifyContent: 'center',
    height: 30,
    paddingHorizontal: 10,
    alignSelf: 'center',
  },
  bottomRefreshTxt: {
    fontSize: respFontSize(12),
    fontWeight: '600',
    color: COLORS.white,
  },
  bottomInApp: {
    fontSize: respFontSize(8),
    fontWeight: '500',
    color: COLORS.gray1,
    textAlign: 'center',
    alignSelf: 'center',
    paddingTop: 2,
  },
  shareView: {
    backgroundColor: COLORS.lightGray,
    paddingVertical: normalize(6),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    width: responsiveWidth(150),
    height: responsiveHeight(40),
    marginVertical: 20,
    borderRadius: 5,
    flexDirection: 'row',
    gap: 10,
  },
  shareImg: {width: responsiveWidth(20), height: responsiveHeight(20)},
  flexOne: {flex: 1},
  shareTxt: {
    textAlign: 'center',
    color: COLORS.blue1,
    fontSize: respFontSize(14),
  },
  closeBtn: {
    height: normalize(28),
    width: normalize(28),
    borderRadius: 20,
    backgroundColor: COLORS.gray3,
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeTxt: {
    fontSize: respFontSize(16),
    color: COLORS.blackGray,
    fontWeight: '400',
    textAlign: 'center',
  },
  refreshView: {flex: 0.24, justifyContent: 'center'},
  logo: {
    height: responsiveHeight(60),
    width: responsiveWidth(60),
    borderRadius: normalize(14),
    alignSelf: 'flex-start',
    borderWidth: 0.4,
    borderColor: COLORS.gray1,
  },
  scrollContainer: {backgroundColor: COLORS.white, paddingTop: 8, flexGrow: 1},
  mainImageView: {
    height: height / 1.7,
    borderBottomWidth: 0.5,
    borderBlockColor: COLORS.lightGray,
  },
  fullSize: {height: '100%', width: '100%'},
});
